filebeat.inputs:
- type: container
  paths: 
    - '/home/ubuntu/Documentos/docker/TCC/V8/pipelineRessarcimento/airflow/*/*.log'
processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

output.elasticsearch:
  hosts: ["172.28.0.14:9200","172.29.0.14:9200" ]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"

logging.json: true
logging.metrics.enabled: false
